server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///aikuiba-aop-log?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      table-prefix: t_
  mapper-locations: classpath:mapper/*Mapper.xml    # 设置Mapper路径
  type-aliases-package: cn.aikuiba.domain   # 实体类别名包
  configuration:
    map-underscore-to-camel-case: true    # 开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志
